class Category():
    categories = [
        "HOME", "KITCHEN", "ELECTRONICS", "CLOTHING", "BOOKS", "FURNITURE", "BEAUTY", "SPORTS & OUTDOORS",
        "TOYS & GAMES", "JEWELRY", "GROCERY", "AUTOMOTIVE", "PET SUPPLIES", "HEALTH & WELLNESS",
        "OFFICE & SCHOOL SUPPLIES"
    ]

