# noinspection PyStatementEffect
{
    "Electronics": {
        "Smartphones & Accessories": ["iPhone 13", "Samsung Galaxy S21", "Google Pixel 6", "OnePlus 9", "Apple AirPods Pro", "Anker Power Bank", "Spigen Phone Case", "Belkin Wireless Charger", "Screen Protector", "Bluetooth Selfie Stick"],
        "Computers & Laptops": ["MacBook Pro", "Dell XPS 13", "Lenovo ThinkPad X1 Carbon", "Asus ROG Gaming Laptop", "Acer Chromebook", "Microsoft Surface Pro", "HP Envy x360", "Apple Magic Mouse", "Logitech Wireless Keyboard", "External Hard Drive"],
        "Cameras & Photography": ["Canon EOS 5D Mark IV", "Sony Alpha a7 III", "Nikon D850", "GoPro Hero 9", "DJI Mavic Air 2", "Manfrotto Tripod", "Lowepro Camera Backpack", "SanDisk SD Card", "Rode VideoMic Pro", "Ring Light"],
        "Televisions & Home Theater": ["LG OLED 4K TV", "Samsung QLED TV", "Sony 65-Inch 4K TV", "Sonos Soundbar", "Roku Streaming Stick", "Apple TV 4K", "Blu-ray Player", "Epson Projector", "Universal Remote Control", "TV Wall Mount"],
        "Audio & Hi-Fi": ["Bose QuietComfort 35 II", "Sony WH-1000XM4", "Audio-Technica Turntable", "Sonos Speaker", "JBL Portable Speaker", "Sennheiser HD 660S", "Pioneer DJ Controller", "Shure Microphone", "FiiO Hi-Res Player", "Harman Kardon Receiver"],
        "Wearable Technology": ["Apple Watch Series 7", "Fitbit Charge 5", "Garmin Fenix 7", "Samsung Galaxy Watch 4", "Oculus Quest 2", "Whoop Strap 4.0", "Withings Body+ Smart Scale", "Amazfit Bip U Pro", "Suunto 7 Smartwatch", "AirPods Max"],
        "Video Games & Consoles": ["PlayStation 5", "Xbox Series X", "Nintendo Switch", "Sony DualSense Controller", "Xbox Wireless Controller", "Nintendo Joy-Con", "PlayStation VR", "Xbox Game Pass Subscription", "Nintendo Switch Pro Controller", "Gaming Headset"],
        "Tablets & E-Readers": ["iPad Pro", "Samsung Galaxy Tab S7", "Amazon Kindle Paperwhite", "Microsoft Surface Go 2", "Huawei MatePad Pro", "Lenovo Tab M10", "Wacom Intuos Graphics Tablet", "Boox Nova Pro E-Reader", "XP-Pen Artist Pro 16", "Onyx Boox Note Air"],
        "Networking & Wireless": ["Google Nest Wifi", "TP-Link Archer C4000 Router", "Linksys Mesh WiFi System", "Netgear Nighthawk Pro Gaming Router", "Ubiquiti UniFi Access Point", "ASUS AX6000 Router", "Eero Pro Mesh WiFi", "Orbi Mesh WiFi System", "MeshForce Whole Home Mesh WiFi", "Archer A7 Dual-Band Router"],
        "Home Automation & Security": ["Ring Video Doorbell Pro", "Nest Learning Thermostat", "Amazon Echo Show", "Philips Hue Smart Bulbs", "August Wi-Fi Smart Lock", "Wyze Cam Outdoor", "SimpliSafe Home Security System", "Eufy RoboVac", "Arlo Pro 4 Security Camera", "Nest Cam Indoor"]
    },
    "Fashion": {
        "Casual Wear": ["Levi's Jeans", "Nike T-Shirt", "Adidas Hoodie", "Converse Sneakers", "Ralph Lauren Polo", "Tommy Hilfiger Jacket", "Calvin Klein Sweatpants", "Under Armour Shorts", "Vans Slip-On", "Columbia Fleece Jacket"],
        "Formal Wear": ["Brooks Brothers Suit", "Hugo Boss Dress Shirt", "Allen Edmonds Oxford Shoes", "Calvin Klein Tie", "Michael Kors Dress", "Ted Baker Blazer", "Rolex Watch", "Burberry Coat", "Ray-Ban Aviator Sunglasses", "Gucci Belt"],
        "Sportswear": ["Lululemon Yoga Pants", "New Balance Running Shoes", "Columbia Sportswear Jacket", "Adidas Soccer Jersey", "Nike Dri-FIT Leggings", "Puma Athletic Shorts", "Reebok CrossFit Shoes", "Oakley Sports Sunglasses", "The North Face Fleece", "Saucony Running Shorts"],
        "Footwear": ["Dr. Martens Boots", "Timberland Waterproof Boots", "Clarks Desert Boots", "Steve Madden Heels", "Birkenstock Sandals", "Skechers Sneakers", "UGG Classic Short Boots", "Converse Chuck Taylor All Star", "Vionic Orthopedic Shoes", "Crocs Classic Clogs"],
        "Accessories": ["Fossil Men's Wallet", "Michael Kors Handbag", "Coach Wallet", "Kate Spade Tote Bag", "Ray-Ban Wayfarer Sunglasses", "Hermès Silk Scarf", "Gucci GG Belt", "Tiffany & Co. Necklace", "Pandora Charm Bracelet", "Rolex Submariner Watch"],
        "Lingerie & Sleepwear": ["Victoria's Secret Bra", "Calvin Klein Boxer Briefs", "Lululemon Yoga Bra", "Tommy John Lounge Pants", "Hanky Panky Thong", "Natori Nightgown", "Hanro Sleep Shirt", "Chantelle Underwire Bra", "Soma Cool Nights Pajamas", "Wacoal Bralette"],
        "Swimwear": ["Speedo Swim Trunks", "Adidas Swimsuit", "TYR Racing Swimsuit", "Roxy Bikini", "Billabong Board Shorts", "Volcom One-Piece Swimsuit", "Rip Curl Rash Guard", "Quiksilver Swim Shorts", "O'Neill Wetsuit", "Columbia Sun Hat"],
        "Ethnic Wear": ["Sari", "Kurta Pajama Set", "Sherwani", "Anarkali Suit", "Salwar Kameez", "Lehenga Choli", "Dhoti Kurta", "Bandhgala Suit", "Ghagra Choli", "Phulkari Dupatta"],
        "Kids' Fashion": ["Carter's Baby Onesies", "OshKosh B'gosh Overalls", "Gap Kids' Jeans", "The Children's Place Dresses", "Nike Kids' Sneakers", "Adidas Kids' Tracksuits", "H&M Kids' Pajamas", "Old Navy Baby Bodysuits", "Carters Toddler Shoes", "Puma Kids' Backpack"]
    },
    "Home & Kitchen": {
        "Cookware & Bakeware": ["Cuisinart Cookware Set", "Pyrex Baking Dish", "KitchenAid Stand Mixer", "Non-Stick Frying Pan", "Instant Pot", "Bundt Cake Pan", "Lodge Cast Iron Skillet", "Bakeware Set", "Dutch Oven", "Wusthof Knife Set"],
        "Kitchen Appliances": ["Breville Toaster Oven", "Keurig Coffee Maker", "Vitamix Blender", "Crock-Pot Slow Cooker", "Ninja Foodi Grill", "Hamilton Beach Food Processor", "Rice Cooker", "Espresso Machine", "Electric Kettle", "Air Fryer"],
        "Dining & Tableware": ["Dinnerware Set", "Flatware Set", "Wine Glasses", "Coffee Mugs", "Glass Tumblers", "Tablecloth", "Napkin Set", "Salt and Pepper Shakers", "Serving Platter", "Champagne Flutes"],
        "Bedding & Linens": ["Egyptian Cotton Sheets", "Memory Foam Mattress Topper", "Duvet Cover Set", "Pillowcases", "Quilt Set", "Bedspread", "Throw Blanket", "Mattress Protector", "Down Comforter", "Bed Skirt"],
        "Home Décor": ["Area Rug", "Wall Clock", "Wall Shelves", "Mirrors", "Canvas Wall Art", "Throw Pillows", "Curtains", "Artificial Plants", "Decorative Vases", "Wall Decals"],
        "Storage & Organization": ["Closet Organizer", "Shoe Rack", "Storage Bins", "Drawer Organizers", "Underbed Storage", "Garage Shelving", "Hanging Closet Organizer", "Plastic Storage Boxes", "Storage Bench", "Toy Storage"],
        "Cleaning Supplies": ["Vacuum Cleaner", "Broom and Dustpan", "Mop and Bucket", "Cleaning Cloths", "Dishwashing Liquid", "Trash Bags", "Cleaning Brushes", "Microfiber Mop Pads", "Sponge Scrubbers", "Toilet Bowl Cleaner"],
        "Home Improvement Tools": ["Cordless Drill", "Toolbox Set", "Screwdriver Set", "Hammer", "Measuring Tape", "Wrench Set", "Pliers", "Utility Knife", "Power Saw", "Level"],
        "Furniture": ["Sofa", "Dining Table Set", "Bed Frame", "Recliner Chair", "Coffee Table", "Bookshelf", "Accent Chair", "TV Stand", "Dresser", "Bar Stools"],
        "Smart Home Devices": ["Amazon Echo", "Google Nest Hub", "Ring Doorbell", "Smart Thermostat", "Wireless Security Camera", "Smart Lock", "Robot Vacuum", "Smart Bulbs", "Smart Plug", "Mesh WiFi System"]
    },
    "Beauty & Personal Care": {
        "Skincare": ["CeraVe Moisturizing Cream", "Neutrogena Hydro Boost Gel-Cream", "The Ordinary Niacinamide Serum", "Cetaphil Gentle Skin Cleanser", "Paula's Choice BHA Liquid Exfoliant", "La Roche-Posay Sunscreen", "Retinol Serum", "Hyaluronic Acid Serum", "Korean Sheet Masks", "Vitamin C Serum"],
        "Haircare": ["Moroccanoil Treatment", "TRESemmé Shampoo and Conditioner", "Olaplex Hair Perfector No. 3", "Dyson Hair Dryer", "Garnier Fructis Hair Mask", "Hair Straightener", "Hair Curling Wand", "Kerastase Hair Oil", "Biotin Supplements", "Dry Shampoo"],
        "Makeup": ["L'Oréal Paris Foundation", "Maybelline Mascara", "NYX Professional Makeup Palette", "Fenty Beauty Concealer", "Urban Decay Eyeshadow Primer", "MAC Lipstick", "Anastasia Beverly Hills Brow Wiz", "Too Faced Blush", "Makeup Brushes Set", "Beauty Blender"],
        "Fragrances": ["Chanel No. 5 Perfume", "Dolce & Gabbana Light Blue", "Yves Saint Laurent Black Opium", "Creed Aventus Cologne", "Jo Malone London Fragrance", "Tom Ford Oud Wood", "Viktor & Rolf Flowerbomb", "Calvin Klein Eternity", "Bvlgari Perfume", "Paco Rabanne 1 Million"],
        "Bath & Body": ["Dove Body Wash", "Aveeno Daily Moisturizing Lotion", "Dr. Bronner's Castile Soap", "Epsom Salt", "Bath Bombs", "Body Scrub", "Shower Loofah", "Lavender Essential Oil", "Bubble Bath", "Natural Deodorant"],
        "Men's Grooming": ["Gillette Fusion5 Razor", "Old Spice Deodorant", "Beard Trimmer", "Men's Shaving Cream", "Manscaped Lawn Mower 4.0", "Baxter of California Pomade", "NIVEA Men Post Shave Balm", "Dapper Dan Hair Styling Cream", "Cremo Beard Oil", "Proraso Shaving Brush"],
        "Oral Care": ["Oral-B Electric Toothbrush", "Crest 3D White Toothpaste", "Listerine Mouthwash", "Philips Sonicare AirFloss", "Waterpik Water Flosser", "Tongue Scraper", "Toothbrush Holder", "Dental Floss Picks", "Teeth Whitening Strips", "Sensitive Toothbrush"],
        "Nail Care": ["OPI Nail Polish", "Sally Hansen Nail Hardener", "Nail File Set", "Cuticle Oil", "Nail Buffer", "Gel Nail Kit", "Nail Dryer", "Nail Art Brushes", "Nail Polish Remover", "Manicure Pedicure Set"],
        "Tools & Accessories": ["Makeup Mirror with Lights", "Cotton Rounds", "Makeup Organizer", "Tweezers Set", "Eyelash Curler", "Pedicure Kit", "Makeup Sponges", "Makeup Brush Cleaner", "Facial Hair Removal Tool", "Cosmetic Bag"],
        "Natural & Organic": ["Organic Coconut Oil", "Shea Moisture Shampoo", "Natural Deodorant Stone", "Argan Oil Hair Serum", "Burt's Bees Lip Balm", "Eco-Friendly Bamboo Toothbrush", "Essential Oil Diffuser", "Organic Lavender Oil", "Natural Bar Soap", "Vegan Makeup Brushes"]
    },
    "Sports & Outdoors": {
        "Fitness & Exercise Equipment": ["Peloton Exercise Bike", "Bowflex Home Gym", "Dumbbell Set", "Yoga Mat", "Resistance Bands", "Exercise Ball", "Jump Rope", "Treadmill", "Rowing Machine", "Kettlebell Set"],
        "Outdoor Recreation": ["Camping Tent", "Hiking Backpack", "Fishing Rod and Reel Combo", "Inflatable Kayak", "Portable Hammock", "Cycling Helmet", "Climbing Harness", "Binoculars", "Portable Grill", "Paddleboard"],
        "Team Sports": ["Basketball", "Soccer Ball", "Football", "Baseball Glove", "Volleyball", "Tennis Racket", "Hockey Stick", "Rugby Ball", "Softball Bat", "Cricket Kit"],
        "Water Sports": ["Swim Goggles", "Snorkeling Gear", "Wetsuit", "Surfboard", "Boogie Board", "Wakeboard", "Water Skiing Equipment", "Life Jacket", "Pool Float", "Kayak Paddle"],
        "Camping & Hiking": ["Sleeping Bag", "Portable Camping Stove", "Headlamp", "Camping Chair", "Trekking Poles", "Camping Cookware Set", "Solar Charger", "Bear Spray", "Hiking Boots", "Backpacking Tent"],
        "Cycling": ["Road Bike", "Mountain Bike", "Bike Helmet", "Bike Lock", "Cycling Shorts", "Bike Lights", "Bike Repair Tool Kit", "Cycling Gloves", "Bike Water Bottle", "Bike Pump"],
        "Golf": ["Golf Clubs Set", "Golf Bag", "Golf Balls", "Golf GPS Watch", "Golf Shoes", "Golf Glove", "Golf Push Cart", "Golf Range Finder", "Putting Green", "Golf Swing Analyzer"],
        "Winter Sports": ["Snowboard", "Ski Set", "Snow Boots", "Ski Goggles", "Snow Gloves", "Ice Skates", "Snow Sled", "Ski Pants", "Snowshoes", "Winter Jacket"],
        "Sports Apparel": ["Athletic Shorts", "Sports Bras", "Compression Socks", "Running Tights", "Sweat-wicking T-shirts", "Performance Hoodies", "Gym Leggings", "Cycling Jerseys", "Basketball Shorts", "Yoga Pants"],
        "Sports Nutrition": ["Protein Powder", "Energy Bars", "Electrolyte Tablets", "Pre-workout Supplements", "Recovery Supplements", "BCAA Supplements", "Hydration Pack", "Energy Gels", "Protein Bars", "Vitamin Supplements"]
    },
    "Automotive": {
        "Car Accessories": ["Car Phone Holder", "Windshield Sun Shade", "Car Seat Covers", "Steering Wheel Cover", "Car Floor Mats", "Car Air Freshener", "Car Charger", "Rooftop Cargo Carrier", "Car Jump Starter", "Car Backseat Organizer"],
        "Motorbike Accessories": ["Motorcycle Helmet", "Motorcycle Gloves", "Motorcycle Jacket", "Motorcycle Boots", "Motorcycle Cover", "Bluetooth Motorcycle Intercom", "Motorcycle Lock", "Motorcycle Phone Mount", "Motorcycle Backpack", "Motorcycle Riding Pants"],
        "Car Parts": ["Brake Pads", "Car Battery", "Spark Plugs", "Oil Filter", "Air Filter", "Car Alternator", "Tire Pressure Gauge", "Car Radiator", "Cabin Air Filter", "Engine Oil"],
        "Tires & Wheels": ["All-Season Tires", "Winter Tires", "Summer Tires", "Tire Chains", "Alloy Wheels", "Spare Tire Cover", "Wheel Spacers", "Wheel Lug Nuts", "Tire Repair Kit", "Tire Inflator"],
        "Oils & Fluids": ["Motor Oil", "Transmission Fluid", "Brake Fluid", "Antifreeze Coolant", "Power Steering Fluid", "Engine Degreaser", "Fuel Injector Cleaner", "Windshield Washer Fluid", "Radiator Stop Leak", "Gear Oil"],
        "Car Electronics": ["Car Stereo System", "GPS & Navigation", "Dash Cam", "Car Alarm System", "Bluetooth Car Adapter", "Car Subwoofer", "Car Amplifier", "Car DVD Player", "Backup Camera", "Car Speakers"],
        "Tools & Equipment": ["Jack Stands", "Car Tool Set", "Torque Wrench", "Car Battery Charger", "Jumper Cables", "Car Diagnostic Scanner", "OBD2 Scanner", "Car Wash Kit", "Car Polishing Kit", "Car Buffer"],
        "Car Care": ["Car Wax", "Car Wash Soap", "Microfiber Towels", "Car Detailing Kit", "Car Interior Cleaner", "Wheel Brush", "Car Tire Cleaner", "Leather Conditioner", "Car Upholstery Cleaner", "Bug and Tar Remover"],
        "Motorcycle Parts": ["Motorcycle Exhaust System", "Motorcycle Chain and Sprocket Kit", "Motorcycle Air Filter", "Motorcycle Brake Disc", "Motorcycle Handlebars", "Motorcycle Fairing Kit", "Motorcycle Battery", "Motorcycle Fuel Pump", "Motorcycle Grips", "Motorcycle Mirrors"],
        "GPS & Navigation": ["Garmin GPS Navigator", "TomTom GPS", "Magellan GPS", "GPS Map Updates", "Garmin InReach Explorer+", "GPS Tracking Device", "Boat GPS", "Hiking GPS", "Truck GPS", "Motorcycle GPS"]
    },
    "Books & Stationery": {
        "Fiction": ["The Great Gatsby by F. Scott Fitzgerald", "To Kill a Mockingbird by Harper Lee", "1984 by George Orwell", "The Catcher in the Rye by J.D. Salinger", "Pride and Prejudice by Jane Austen", "The Hobbit by J.R.R. Tolkien", "The Alchemist by Paulo Coelho", "Harry Potter and the Sorcerer's Stone by J.K. Rowling", "The Girl on the Train by Paula Hawkins", "The Da Vinci Code by Dan Brown"],
        "Non-Fiction": ["Sapiens: A Brief History of Humankind by Yuval Noah Harari", "Becoming by Michelle Obama", "Educated by Tara Westover", "Born a Crime by Trevor Noah", "The Immortal Life of Henrietta Lacks by Rebecca Skloot", "The Subtle Art of Not Giving a F*ck by Mark Manson", "The Power of Habit by Charles Duhigg", "Bad Blood: Secrets and Lies in a Silicon Valley Startup by John Carreyrou", "Quiet: The Power of Introverts in a World That Can't Stop Talking by Susan Cain", "Into the Wild by Jon Krakauer"],
        "Children's Books": ["Where the Wild Things Are by Maurice Sendak", "Goodnight Moon by Margaret Wise Brown", "Charlotte's Web by E.B. White", "Harry Potter and the Philosopher's Stone by J.K. Rowling", "Matilda by Roald Dahl", "The Cat in the Hat by Dr. Seuss", "Alice's Adventures in Wonderland by Lewis Carroll", "The Very Hungry Caterpillar by Eric Carle", "Winnie-the-Pooh by A.A. Milne", "The Gruffalo by Julia Donaldson"],
        "Academic & Textbooks": ["Introduction to Psychology by James W. Kalat", "Calculus: Early Transcendentals by James Stewart", "Chemistry: The Central Science by Theodore L. Brown", "Principles of Economics by N. Gregory Mankiw", "Campbell Biology by Jane B. Reece", "The Elements of Style by William Strunk Jr. and E.B. White", "Organic Chemistry by Paula Yurkanis Bruice", "Physics for Scientists and Engineers by Raymond A. Serway", "Microeconomics by Paul Krugman and Robin Wells", "A History of Western Philosophy by Bertrand Russell"],
        "Journals & Diaries": ["Moleskine Classic Notebook", "Leuchtturm1917 Hardcover Journal", "Bullet Journal by Ryder Carroll", "Five Minute Journal by Intelligent Change", "Artists Sketchbook", "Travelers Notebook", "Dream Journal", "Gratitude Journal", "Food Diary", "Happiness Planner"],
        "Art Supplies": ["Acrylic Paint Set", "Watercolor Paint Set", "Sketching Pencils Set", "Oil Paint Set", "Canvas Panels", "Watercolor Paper Pad", "Colored Pencils Set", "Calligraphy Pens Set", "Pastel Set", "Art Easel"],
        "Office Supplies": ["Ballpoint Pens", "Notebooks", "Stapler", "Paper Clips", "Desk Organizer", "File Folders", "Whiteboard and Dry Erase Markers", "Desk Calendar", "Post-it Notes", "Desktop Computer"],
        "Calendars & Planners": ["2023 Monthly Planner", "Wall Calendar", "Desk Pad Calendar", "Yearly Planner", "Daily Planner", "Weekly Planner", "Pocket Calendar", "Family Calendar", "Academic Planner", "Business Planner"],
        "Greeting Cards": ["Birthday Cards", "Anniversary Cards", "Thank You Cards", "Wedding Cards", "Sympathy Cards", "Graduation Cards", "Baby Shower Cards", "Valentine's Day Cards", "Christmas Cards", "Blank Cards"],
        "Writing Instruments": ["Fountain Pen", "Rollerball Pen", "Gel Pen Set", "Calligraphy Set", "Mechanical Pencils", "Highlighters", "Markers", "Coloring Pencils", "Brush Pens", "Chalk"]
    },
    "Toys & Games": {
        "Educational Toys": ["LEGO Education STEM Kit", "Magnetic Building Blocks", "Science Experiment Kits", "Puzzle Games", "Educational Board Games", "Robotics Kits", "Microscope for Kids", "Math Learning Toys", "Language Learning Toys", "Coding Robot Toy"],
        "Board Games & Puzzles": ["Settlers of Catan Board Game", "Ticket to Ride Board Game", "Codenames Board Game", "Jigsaw Puzzles", "Chess Set", "Dominion Card Game", "Risk Board Game", "Scrabble", "Carcassonne Board Game", "Pandemic Board Game"],
        "Action Figures & Collectibles": ["Action Figures (Marvel, Star Wars, etc.)", "Funko Pop! Vinyl Figures", "Hot Wheels Cars", "Transformers Action Figures", "Collectible Figurines", "Pokémon Cards", "LEGO Minifigures", "Nerf Blasters", "Trading Cards", "Miniature Model Kits"],
        "Dolls & Plush Toys": ["Barbie Dolls", "Teddy Bears", "Baby Dolls", "Rag Dolls", "Action Figure Dolls", "Dollhouses", "Plush Stuffed Animals", "Doll Accessories", "Fashion Dolls", "Interactive Dolls"],
        "Outdoor Play": ["Swing Set", "Trampoline", "Playground Slide", "Sandbox", "Basketball Hoop", "Scooters", "Kites", "Bouncy Castle", "Water Guns", "Sidewalk Chalk"],
        "Electronic Toys": ["Remote-Controlled Cars", "Drones", "Robotic Pets", "Interactive Learning Tablets", "Toy Robots", "Walkie-Talkies", "Musical Instruments for Kids", "Electronic Pets", "Augmented Reality Toys", "Virtual Reality Headsets for Kids"],
        "Building & Construction Toys": ["LEGO Sets", "Mega Bloks", "K'NEX Building Sets", "Magnetic Tiles", "Building Blocks", "Architecture Model Kits", "Marble Run Sets", "Brick Building Sets", "Geometric Construction Sets", "Engineering Building Kits"],
        "Arts & Crafts": ["Art Supplies Set for Kids", "Craft Kits", "DIY Jewelry Making Kits", "Paint by Numbers Kits", "Pottery Wheel Kits", "Sewing Kits", "Origami Paper Set", "Bead Kits", "Wooden Craft Kits", "Tie-Dye Kits"],
        "Pretend Play": ["Play Kitchen Sets", "Doctor's Kits", "Tool Sets for Kids", "Dress-Up Costumes", "Superhero Capes", "Toy Cash Registers", "Play Food Sets", "Firefighter Playset", "Tea Party Sets", "Toy Workbenches"],
        "Remote Control Toys": ["RC Cars", "RC Helicopters", "RC Boats", "RC Airplanes", "RC Tanks", "RC Construction Vehicles", "RC Quadcopters", "RC Racing Drones", "RC Monster Trucks", "RC Submarines"]
    },
    "Grocery & Gourmet Food": {
        "Fresh Produce": ["Apples", "Bananas", "Strawberries", "Avocado", "Lettuce", "Tomatoes", "Broccoli", "Carrots", "Bell Peppers", "Oranges"],
        "Bakery & Bread": ["Baguette", "Sourdough Bread", "Croissants", "Whole Wheat Bread", "Brioche", "Cinnamon Rolls", "Multigrain Bread", "Ciabatta", "Pita Bread", "Kaiser Rolls"],
        "Dairy & Eggs": ["Milk", "Eggs", "Butter", "Cheese (Cheddar, Swiss, etc.)", "Yogurt", "Sour Cream", "Heavy Cream", "Cottage Cheese", "Whipped Cream", "Cream Cheese"],
        "Meat & Seafood": ["Chicken Breast", "Salmon Fillet", "Ground Beef", "Shrimp", "Pork Chops", "Lamb Rack", "Bacon", "Lobster Tail", "Turkey", "Tilapia Fillet"],
        "Pantry Staples": ["Rice", "Pasta (Spaghetti, Penne, etc.)", "Canned Tomatoes", "Canned Beans", "Olive Oil", "Flour", "Sugar", "Salt", "Spices (Cumin, Paprika, etc.)", "Honey"],
        "Snacks & Sweets": ["Potato Chips", "Chocolate Bars", "Candy (Gummy Bears, M&M's, etc.)", "Popcorn", "Granola Bars", "Trail Mix", "Cookies", "Nuts (Almonds, Cashews, etc.)", "Dried Fruits", "Ice Cream"],
        "Beverages": ["Coffee Beans", "Black Tea", "Green Tea", "Soda (Coke, Pepsi, etc.)", "Bottled Water", "Juice (Orange Juice, Apple Juice, etc.)", "Energy Drinks", "Wine (Red, White, Rosé)", "Beer (IPA, Lager, etc.)", "Seltzer Water"],
        "Organic Foods": ["Organic Vegetables", "Organic Fruits", "Organic Dairy Products", "Organic Grains (Quinoa, Oats, etc.)", "Organic Snacks", "Organic Meat", "Organic Eggs", "Organic Baby Food", "Organic Pasta", "Organic Cereals"],
        "International Foods": ["Sushi Ingredients", "Mexican Cuisine Ingredients", "Indian Cuisine Ingredients", "Thai Cuisine Ingredients", "Italian Pasta and Sauces", "Chinese Cuisine Ingredients", "Greek Cuisine Ingredients", "Middle Eastern Cuisine Ingredients", "Japanese Ramen Ingredients", "Mediterranean Cuisine Ingredients"],
        "Special Diet Foods": ["Gluten-Free Products", "Vegan Snacks", "Keto-Friendly Foods", "Paleo Diet Foods", "Low-Sodium Products", "Sugar-Free Snacks", "Dairy-Free Alternatives", "Nut-Free Products", "Organic Gluten-Free Bread", "Plant-Based Protein"]
    },
    "Health & Wellness": {
        "Supplements & Vitamins": ["Multivitamins", "Vitamin C Supplements", "Vitamin D Supplements", "Omega-3 Fish Oil Supplements", "Probiotics", "Collagen Supplements", "Iron Supplements", "Biotin Supplements", "Calcium Supplements", "Magnesium Supplements"],
        "Personal Care": ["Shampoo and Conditioner", "Body Wash", "Deodorant", "Toothpaste", "Facial Cleanser", "Moisturizing Lotion", "Sunscreen", "Hand Sanitizer", "Feminine Hygiene Products", "Shaving Cream"],
        "Fitness & Yoga Equipment": ["Yoga Mat", "Resistance Bands", "Dumbbells", "Exercise Ball", "Jump Rope", "Kettlebells", "Resistance Tubes", "Foam Roller", "Pull-Up Bar", "Weight Bench"],
        "Health Monitors & Devices": ["Blood Pressure Monitor", "Digital Thermometer", "Fitness Tracker", "Smart Scale", "Pulse Oximeter", "Blood Glucose Monitor", "Sleep Tracker", "EKG Monitor", "TENS Unit", "Peak Flow Meter"],
        "Weight Management": ["Weight Loss Supplements", "Meal Replacement Shakes", "Digital Kitchen Scale", "Body Fat Scale", "Waist Trainer Belt", "Portion Control Plates", "Appetite Suppressant", "Calorie Counter App", "Bathroom Scale", "Food Scale"],
        "Herbal & Alternative Remedies": ["Essential Oils", "Herbal Tea", "Aromatherapy Diffuser", "Acupressure Mat", "Homeopathic Remedies", "Chinese Herbal Medicine", "Ayurvedic Herbs", "CBD Oil", "Magnetic Therapy Products", "Detox Foot Pads"],
        "Sexual Wellness": ["Condoms", "Personal Lubricants", "Sex Toys", "Kegel Exercisers", "Performance Enhancement Supplements", "Intimate Massagers", "Vibrators", "Lingerie", "Erectile Dysfunction Pumps", "Sexual Health Books"],
        "First Aid & Medical Supplies": ["First Aid Kit", "Adhesive Bandages", "Antiseptic Wipes", "Medical Tape", "Gauze Pads", "CPR Face Shield", "Tweezers", "Instant Cold Packs", "Burn Cream", "Digital Thermometer"],
        "Mental Wellness": ["Meditation Apps", "Stress Relief Toys", "Aromatherapy Candles", "Mindfulness Books", "Journaling Prompts", "Self-Help Books", "Anxiety Relief Supplements", "Therapy and Counseling Services", "Relaxation Techniques", "Gratitude Journals"],
        "Sleep Aids": ["Sleep Masks", "White Noise Machines", "Melatonin Supplements", "Sleep-Inducing Teas", "Earplugs", "Sleep Tracker Watches", "Sleeping Pills", "Weighted Blankets", "Sleep Hygiene Books", "CBD Sleep Products"]
    },
    "Pet Supplies": {
        "Dog Supplies": ["Dog Food", "Dog Treats", "Dog Toys", "Dog Collars and Leashes", "Dog Beds", "Dog Grooming Supplies", "Dog Bowls and Feeders", "Dog Training Aids", "Dog Clothing and Accessories", "Dog Health and Wellness Products"],
        "Cat Supplies": ["Cat Food", "Cat Treats", "Cat Toys", "Cat Litter and Accessories", "Cat Beds", "Cat Grooming Supplies", "Cat Bowls and Feeders", "Cat Carriers and Travel Products", "Cat Scratching Posts", "Cat Health and Wellness Products"],
        "Fish & Aquarium": ["Fish Food", "Aquariums", "Fish Tank Filters and Accessories", "Aquarium Decorations", "Aquarium Heaters", "Aquarium Air Pumps", "Fish Tank Cleaning Supplies", "Fish Medications", "Aquarium Test Kits", "Live Aquarium Plants"],
        "Small Animal Supplies": ["Rabbit Hutches", "Guinea Pig Cages", "Hamster Cages", "Ferret Supplies", "Small Animal Bedding", "Small Animal Food", "Small Animal Toys", "Small Animal Carriers", "Small Animal Treats", "Small Animal Health and Wellness Products"],
        "Bird Supplies": ["Bird Cages", "Bird Food", "Bird Toys", "Bird Perches", "Bird Cage Accessories", "Bird Nesting Supplies", "Bird Grooming Supplies", "Bird Feeders", "Bird Baths", "Bird Health and Wellness Products"],
        "Reptile & Amphibian Supplies": ["Reptile Terrariums", "Reptile Food", "Reptile Heating and Lighting", "Reptile Substrates", "Reptile Decorations", "Reptile Cage Accessories", "Reptile Handling and Health Supplies", "Amphibian Habitats", "Reptile and Amphibian Heating Pads", "Reptile and Amphibian Food Bowls"],
        "Horse Supplies": ["Horse Feed", "Horse Tack and Equipment", "Horse Grooming Supplies", "Horse Health and Wellness Products", "Horse Blankets and Sheets", "Horse Riding Gear", "Horse Stall Supplies", "Horse Pest Control Products", "Horse Trailer Accessories", "Horse Gifts and Decor"],
        "Pet Food & Treats": ["Wet Dog Food", "Dry Cat Food", "Grain-Free Pet Food", "Natural Pet Food", "Healthy Dog Treats", "Grain-Free Cat Treats", "Prescription Pet Food", "Raw Pet Food", "Organic Pet Food", "Hypoallergenic Pet Food"],
        "Pet Grooming": ["Pet Shampoo and Conditioner", "Pet Brushes and Combs", "Pet Nail Clippers", "Pet Grooming Tables", "Pet Hair Clippers", "Pet Ear and Eye Cleaners", "Pet Bathing Tools", "Pet Dental Care Products", "Pet Grooming Gloves", "Pet Towels and Dryers"],
        "Pet Health & Wellness": ["Flea and Tick Control Products", "Heartworm Preventatives", "Joint Supplements for Pets", "Pet Vitamins and Supplements", "Pet Dental Care Products", "Pet Allergy Relief", "Pet Antibiotics", "Pet Pain Relief Medications", "Pet First Aid Kits", "Pet Thermometers"]
    },
    "Gardening & Outdoor Living": {
        "Plants & Seeds": ["Flower Seeds", "Vegetable Plants", "Fruit Trees", "Herb Plants", "Bulb Flowers", "Succulent Plants", "Indoor Plants", "Shrubs and Bushes", "Grass Seeds", "Cactus Plants"],
        "Garden Tools": ["Garden Shovel", "Pruning Shears", "Rakes", "Garden Gloves", "Hedge Trimmers", "Garden Hoes", "Wheelbarrows", "Garden Trowel", "Weed Pullers", "Garden Carts"],
        "Outdoor Furniture": ["Patio Sets", "Outdoor Sofas", "Adirondack Chairs", "Outdoor Dining Tables", "Sun Loungers", "Hammocks", "Fire Pit Tables", "Garden Benches", "Outdoor Swings", "Porch Rocking Chairs"],
        "Grills & Outdoor Cooking": ["Gas Grills", "Charcoal Grills", "Smokers", "Grill Accessories", "Grill Covers", "Outdoor Pizza Ovens", "Firewood Racks", "Grill Thermometers", "Grilling Tools", "Grill Mats"],
        "Pools & Water Fun": ["Above-Ground Pools", "Inflatable Pools", "Pool Floats and Loungers", "Pool Toys", "Pool Cleaners", "Pool Chemicals", "Pool Covers", "Swimming Goggles", "Water Slides", "Hot Tubs and Spas"],
        "Landscaping & Décor": ["Garden Statues", "Outdoor Fountains", "Garden Gnomes", "Solar Lights", "Wind Chimes", "Outdoor Clocks", "Garden Bridges", "Outdoor Wall Art", "Outdoor Planters", "Decorative Stones"],
        "Pest Control": ["Mosquito Repellents", "Bug Zappers", "Rodent Traps", "Insecticides", "Animal Repellents", "Garden Netting", "Plant Protection Covers", "Ant Baits", "Slug and Snail Control", "Beekeeping Supplies"],
        "Outdoor Lighting": ["Solar Pathway Lights", "LED Landscape Lighting", "Outdoor Wall Lights", "Deck Lighting", "String Lights", "Floodlights", "Motion Sensor Lights", "Patio Umbrella Lights", "Garden Lanterns", "Tiki Torches"],
        "Garden Structures": ["Greenhouses", "Garden Arbors", "Garden Trellises", "Pergolas", "Garden Sheds", "Gazebo Tents", "Raised Garden Beds", "Potting Benches", "Fencing and Borders", "Compost Bins"],
        "Hydroponics & Greenhouses": ["Hydroponic Grow Kits", "Hydroponic Nutrients", "Hydroponic Lighting", "Hydroponic Growing Mediums", "Hydroponic Reservoirs", "Hydroponic pH Testers", "Hydroponic Timers", "Greenhouse Kits", "Greenhouse Heaters", "Greenhouse Fans"]
    },
    "Music & Entertainment": {
        "Musical Instruments": ["Acoustic Guitars", "Electric Guitars", "Keyboards", "Digital Pianos", "Violins", "Drum Sets", "Saxophones", "Trumpets", "Synthesizers", "Flutes"],
        "Recording & Studio Equipment": ["Audio Interfaces", "Studio Monitors", "Microphones", "MIDI Controllers", "Digital Audio Workstations (DAWs)", "Studio Headphones", "Pop Filters", "Studio Mixer Boards", "External Hard Drives for Recording", "Acoustic Treatment Panels"],
        "Streaming Services": ["Spotify Premium Subscription", "Apple Music Subscription", "Amazon Music Unlimited Subscription", "Tidal HiFi Subscription", "YouTube Premium Subscription", "Deezer Premium Subscription", "Pandora Plus Subscription", "SoundCloud Go+ Subscription", "Napster Premium Subscription", "Qobuz Studio Subscription"],
        "Concert & Event Tickets": ["Concert Tickets", "Theater Show Tickets", "Sports Event Tickets", "Music Festival Passes", "Comedy Show Tickets", "Broadway Tickets", "Movie Theater Tickets", "Museum Exhibit Tickets", "Amusement Park Tickets", "Art Gallery Admission"],
        "Movies & TV Shows": ["Blu-ray Movies", "DVD Box Sets", "4K Ultra HD Movies", "Movie Streaming Services", "TV Series DVDs", "Movie Posters", "Movie Collectibles", "Classic Film Collections", "Movie Soundtracks", "Movie Popcorn Makers"],
        "Books & Magazines": ["Bestselling Novels", "Non-Fiction Books", "Cookbooks", "Self-Help Books", "Comic Books", "Magazine Subscriptions", "Graphic Novels", "Children's Books", "Biographies", "Science Fiction & Fantasy Books"],
        "Board Games & Puzzles": ["Board Games (Strategy, Family, etc.)", "Jigsaw Puzzles", "Card Games (Uno, Poker, etc.)", "Chess Sets", "Role-Playing Games (D&D, Pathfinder, etc.)", "Cooperative Board Games", "Classic Board Games (Monopoly, Scrabble, etc.)", "Board Game Accessories (Dice, Tokens, etc.)", "Educational Board Games", "Party Games (Cards Against Humanity, etc.)"],
        "Collectibles & Memorabilia": ["Collectible Action Figures", "Sports Memorabilia (Jerseys, Cards, etc.)", "Comic Book Collectibles", "Movie and TV Show Collectibles", "Music Artist Memorabilia", "Historical Memorabilia", "Autographed Items (Sports, Celebrities, etc.)", "Vintage Collectibles", "Pop Culture Memorabilia", "Rare Coins and Stamps"],
        "Vinyl Records & CDs": ["Vinyl Records (Rock, Jazz, etc.)", "CD Albums", "Vinyl Record Players", "Turntable Accessories", "Vinyl Record Storage", "CD Storage Cases", "Vinyl Cleaning Kits", "Music Posters", "Vinyl Record Frames", "Vinyl Record Collector's Accessories"],
        "Electronic Entertainment": ["Video Game Consoles (PS5, Xbox Series X, etc.)", "Video Games (Action, RPG, etc.)", "Gaming Accessories (Controllers, Headsets, etc.)", "Virtual Reality Headsets", "Gaming PCs", "Streaming Devices (Roku, Fire TV, etc.)", "Online Subscriptions (Xbox Game Pass, PlayStation Plus, etc.)", "Gaming Merchandise", "Game Streaming Services (Twitch, YouTube Gaming, etc.)", "Gaming Chairs"]
    },
    "Furniture & Home Decor": {
        "Sofas & Couches": ["Sectional Sofas", "Sleeper Sofas", "Reclining Sofas", "Loveseats", "Chaise Lounges", "Settees", "Futons", "Chesterfield Sofas", "Mid-Century Modern Sofas", "Leather Sofas"],
        "Beds & Bedroom Furniture": ["Platform Beds", "Bunk Beds", "Murphy Beds", "Daybeds", "Headboards", "Dressers", "Nightstands", "Bedroom Sets", "Mattresses", "Bedroom Armoires"],
        "Tables & Chairs": ["Dining Tables", "Dining Chairs", "Coffee Tables", "End Tables", "Console Tables", "Bar Stools", "Kitchen Islands", "Dining Sets", "Accent Chairs", "Side Tables"],
        "Storage & Organization": ["Bookcases", "Shelving Units", "Storage Cabinets", "Closet Organizers", "Storage Bins", "Drawer Organizers", "Floating Shelves", "Garage Storage Systems", "Jewelry Organizers", "Pantry Shelving"],
        "Lighting & Lamps": ["Table Lamps", "Floor Lamps", "Chandeliers", "Pendant Lights", "Ceiling Fans with Lights", "Wall Sconces", "String Lights", "Desk Lamps", "Hanging Lights", "Vanity Lighting"],
        "Wall Art & Decor": ["Canvas Art Prints", "Wall Decals", "Metal Wall Art", "Framed Posters", "Wall Clocks", "Mirrors", "Tapestries", "Wooden Wall Art", "Wall Sculptures", "3D Wall Panels"],
        "Rugs & Carpets": ["Area Rugs", "Runner Rugs", "Outdoor Rugs", "Shag Rugs", "Wool Carpets", "Jute Rugs", "Persian Rugs", "Sisal Rugs", "Braided Rugs", "Kids' Rugs"],
        "Home Textiles": ["Bedding Sets", "Duvet Covers", "Pillow Shams", "Throw Blankets", "Curtains", "Window Blinds", "Tablecloths", "Napkins", "Towels", "Area Rug Pads"],
        "Outdoor Furniture": ["Outdoor Dining Sets", "Outdoor Sofas", "Adirondack Chairs", "Outdoor Tables", "Hammocks", "Outdoor Benches", "Patio Umbrellas", "Outdoor Lounge Chairs", "Fire Pit Sets", "Outdoor Bar Furniture"],
        "Office Furniture": ["Office Desks", "Office Chairs", "Bookcases", "File Cabinets", "Office Cubicles", "Conference Tables", "Office Workstations", "Reception Desks", "Ergonomic Office Chairs", "Computer Desks"]
    },
    "Jewelry & Accessories": {
        "Necklaces & Pendants": ["Diamond Necklaces", "Gold Necklaces", "Silver Necklaces", "Pearl Necklaces", "Initial Necklaces", "Nameplate Necklaces", "Heart Necklaces", "Cross Necklaces", "Choker Necklaces", "Gemstone Necklaces"],
        "Rings": ["Engagement Rings", "Wedding Rings", "Promise Rings", "Cocktail Rings", "Birthstone Rings", "Solitaire Rings", "Stackable Rings", "Statement Rings", "Midi Rings", "Toe Rings"],
        "Earrings": ["Stud Earrings", "Hoop Earrings", "Dangle Earrings", "Chandelier Earrings", "Ear Cuffs", "Threader Earrings", "Statement Earrings", "Ear Jackets", "Tassel Earrings", "Pearl Earrings"],
        "Bracelets & Bangles": ["Bangle Bracelets", "Cuff Bracelets", "Charm Bracelets", "Tennis Bracelets", "Anklets", "Beaded Bracelets", "Chain Bracelets", "Wrap Bracelets", "Link Bracelets", "ID Bracelets"],
        "Watches": ["Analog Watches", "Digital Watches", "Smartwatches", "Automatic Watches", "Chronograph Watches", "Dress Watches", "Sports Watches", "Fashion Watches", "Fitness Trackers", "Pocket Watches"],
        "Fine Jewelry": ["Diamond Jewelry", "Gold Jewelry", "Silver Jewelry", "Platinum Jewelry", "Gemstone Jewelry", "Pearl Jewelry", "Designer Jewelry", "Custom Jewelry", "Wedding Jewelry Sets", "Luxury Watches"],
        "Fashion Jewelry": ["Costume Jewelry", "Statement Jewelry", "Boho Jewelry", "Vintage Jewelry", "Hippie Jewelry", "Art Deco Jewelry", "Retro Jewelry", "Ethnic Jewelry", "Tribal Jewelry", "Gothic Jewelry"],
        "Handbags & Wallets": ["Tote Bags", "Shoulder Bags", "Crossbody Bags", "Clutch Purses", "Hobo Bags", "Backpack Purses", "Satchel Bags", "Wristlet Wallets", "Cardholder Wallets", "Designer Handbags"],
        "Sunglasses": ["Aviator Sunglasses", "Wayfarer Sunglasses", "Cat-Eye Sunglasses", "Round Sunglasses", "Oversized Sunglasses", "Sport Sunglasses", "Polarized Sunglasses", "Mirrored Sunglasses", "Bamboo Sunglasses", "Vintage Sunglasses"],
        "Scarves & Wraps": ["Cashmere Scarves", "Silk Scarves", "Pashmina Wraps", "Infinity Scarves", "Blanket Scarves", "Knit Scarves", "Wool Wraps", "Summer Shawls", "Faux Fur Stoles", "Lace Scarves"]
    },
    "Office Supplies": {
        "Writing Instruments": ["Ballpoint Pens", "Gel Pens", "Fountain Pens", "Rollerball Pens", "Mechanical Pencils", "Colored Pencils", "Highlighters", "Markers", "Calligraphy Pens", "Fineliner Pens"],
        "Paper Products": ["Notebooks", "Notepads", "Journals", "Legal Pads", "Sketchbooks", "Printer Paper", "Index Cards", "Sticky Notes", "Construction Paper", "Graph Paper"],
        "Desk Accessories": ["Desk Organizers", "Desk Sets", "Desk Mats", "Pen Holders", "File Organizers", "Desk Clocks", "Desk Lamps", "Desk Nameplates", "Desk Plants", "Cable Management"],
        "Organizers & Planners": ["Planners", "Calendars", "Appointment Books", "To-Do Lists", "Address Books", "Day Planners", "Weekly Planners", "Monthly Planners", "Yearly Planners", "Desk Calendars"],
        "Printers & Scanners": ["Inkjet Printers", "Laser Printers", "All-in-One Printers", "Label Printers", "Receipt Printers", "Document Scanners", "Flatbed Scanners", "Portable Scanners", "Photo Printers", "Wide-Format Printers"],
        "Office Furniture": ["Office Desks", "Office Chairs", "File Cabinets", "Bookcases", "Office Cubicles", "Conference Tables", "Office Workstations", "Reception Desks", "Ergonomic Office Chairs", "Computer Desks"],
        "Office Electronics": ["Computers", "Laptops", "Monitors", "Keyboards", "Mice", "Headsets", "Webcams", "External Hard Drives", "Printers", "Scanners"],
        "Binders & Folders": ["Binders", "File Folders", "Expanding Files", "Ring Binders", "Classification Folders", "Presentation Binders", "Report Covers", "Portfolio Cases", "Sheet Protectors", "Dividers"],
        "Mailing & Shipping Supplies": ["Shipping Boxes", "Bubble Mailers", "Packing Tape", "Envelopes", "Packing Peanuts", "Mailing Labels", "Shipping Scales", "Postal Tubes", "Poly Mailers", "Mailroom Carts"],
        "Educational Supplies": ["Teaching Supplies", "Educational Toys", "Classroom Decorations", "Teaching Aids", "Art Supplies for Schools", "School Furniture", "School Storage", "STEM Education Kits", "Preschool Supplies", "Teacher Resources"]
    },
    "Travel & Luggage": {
        "Suitcases & Travel Bags": ["Hardside Suitcases", "Softside Suitcases", "Carry-On Luggage", "Checked Luggage", "Rolling Duffel Bags", "Garment Bags", "Weekender Bags", "Travel Totes", "Laptop Backpacks", "Kids' Luggage"],
        "Backpacks": ["Travel Backpacks", "Daypacks", "Hiking Backpacks", "Laptop Backpacks", "School Backpacks", "Hydration Packs", "Camera Backpacks", "Drawstring Backpacks", "Rolling Backpacks", "Tactical Backpacks"],
        "Travel Accessories": ["Luggage Tags", "Travel Pillows", "Travel Wallets", "Travel Locks", "Compression Socks", "Travel Bottles", "Toiletry Bags", "Travel Adapters", "Luggage Straps", "Travel Scale"],
        "Travel Electronics": ["Travel Chargers", "Power Banks", "Noise-Canceling Headphones", "Portable Wi-Fi Hotspots", "Travel Adapters", "Travel Speakers", "Tablet Holders", "GPS Navigation Devices", "Travel Laptops", "Travel Cameras"],
        "Camping & Hiking Gear": ["Tents", "Sleeping Bags", "Backpacks", "Camping Stoves", "Portable Grills", "Hiking Boots", "Camping Chairs", "Hiking Poles", "Camp Cookware", "Camping Lanterns"],
        "Travel Clothing": ["Travel Jackets", "Convertible Pants", "Travel Shirts", "Packable Rain Jackets", "Travel Dresses", "Quick-Dry Underwear", "Travel Pants", "Hiking Shorts", "Sun Hats", "Travel Socks"],
        "Travel Books & Guides": ["Travel Guidebooks", "Language Phrasebooks", "Travel Memoirs", "Travel Maps", "City Guides", "Outdoor Adventure Guides", "Travel Photography Books", "Road Trip Guides", "Cultural Exploration Books", "Solo Travel Guides"],
        "Maps & Navigation": ["Road Maps", "Topographic Maps", "GPS Devices", "Car GPS Navigation Systems", "Bike GPS Devices", "Hiking GPS Units", "Maps for National Parks", "Marine Navigation Charts", "Aeronautical Charts", "City Maps"],
        "Travel Security": ["Travel Locks", "RFID Blocking Wallets", "Money Belts", "Anti-Theft Backpacks", "TSA-Approved Locks", "Portable Safes", "Security Pouches", "Luggage Straps with Locks", "Hotel Room Door Alarms", "Travel Door Locks"],
        "Specialty Luggage": ["Ski Bags", "Snowboard Bags", "Golf Travel Bags", "Bike Travel Cases", "Fishing Rod Cases", "Golf Club Travel Bags", "Scuba Diving Bags", "Surfboard Bags", "Wine Bottle Travel Cases", "Musical Instrument Cases"]
    },
    "Crafts & Hobbies": {
        "Painting & Drawing Supplies": ["Acrylic Paints", "Watercolor Paints", "Oil Paints", "Colored Pencils", "Sketch Pencils", "Drawing Paper", "Canvas Panels", "Paintbrushes", "Palette Knives", "Easels"],
        "Sewing & Fabric": ["Sewing Machines", "Sewing Threads", "Fabric Scissors", "Quilting Supplies", "Embroidery Kits", "Sewing Patterns", "Fabric Paints", "Fabric Dyes", "Sewing Needles", "Iron-On Patches"],
        "Knitting & Crochet": ["Knitting Needles", "Crochet Hooks", "Yarn", "Knitting Kits", "Crochet Kits", "Knitting Accessories", "Crochet Accessories", "Knitting Patterns", "Crochet Patterns", "Yarn Storage"],
        "Scrapbooking & Paper Crafts": ["Scrapbook Paper", "Die-Cutting Machines", "Embossing Machines", "Stamps and Ink Pads", "Cardstock Paper", "Scrapbooking Kits", "Paper Punches", "Scrapbook Stickers", "Washi Tape", "Photo Albums"],
        "Jewelry Making": ["Beads", "Jewelry Wire", "Jewelry Findings", "Pliers and Tools", "Jewelry Making Kits", "Charms and Pendants", "Seed Beads", "Gemstone Beads", "Metal Stamping Kits", "Jewelry Organizers"],
        "Woodworking": ["Power Tools", "Hand Tools", "Wood Lumber", "Woodworking Plans", "Wood Finishes", "Wood Glue", "Wood Carving Tools", "Woodworking Vises", "Woodworking Books", "Woodworking Jigs"],
        "Model Building": ["Model Kits (Cars, Planes, Ships, etc.)", "Model Paints", "Model Glue", "Model Tools", "Model Accessories", "Diorama Supplies", "Scale Model Figures", "Model Building Books", "Plastic Model Kits", "Wooden Model Kits"],
        "Collectibles": ["Collectible Figurines", "Collectible Coins", "Collectible Stamps", "Collectible Action Figures", "Sports Collectibles", "Comic Book Collectibles", "Collectible Cards (Trading Cards, Playing Cards, etc.)", "Collectible Dolls", "Collectible Pins", "Collectible Art Prints"],
        "Photography": ["Digital Cameras", "DSLR Cameras", "Mirrorless Cameras", "Camera Lenses", "Camera Tripods", "Camera Bags", "Memory Cards", "Camera Filters", "Camera Flashes", "Photography Books"],
        "Candle & Soap Making": ["Candle Wax", "Candle Wicks", "Candle Molds", "Candle Fragrance Oils", "Soap Bases", "Soap Molds", "Soap Colors", "Candle Making Kits", "Soap Making Kits", "Candle Dyes"]
    },
    "Baby Products": {
        "Baby Clothing & Accessories": ["Baby Onesies", "Baby Rompers", "Baby Sleepsuits", "Baby Bodysuits", "Baby Pajamas", "Baby Socks", "Baby Hats", "Baby Mittens", "Baby Booties", "Baby Bibs"],
        "Diapers & Wipes": ["Disposable Diapers", "Cloth Diapers", "Diaper Bags", "Diaper Pails", "Baby Wipes", "Diaper Rash Creams", "Changing Pads", "Diaper Liners", "Swim Diapers", "Training Pants"],
        "Feeding & Nursing": ["Baby Bottles", "Breast Pumps", "Nursing Bras", "Baby Formula", "Nursing Covers", "Bottle Warmers", "Bottle Sterilizers", "Baby Food", "Baby Spoons", "High Chairs"],
        "Strollers & Car Seats": ["Baby Strollers", "Travel Systems (Stroller & Car Seat)", "Jogging Strollers", "Umbrella Strollers", "Convertible Car Seats", "Infant Car Seats", "Booster Car Seats", "Car Seat Bases", "Car Seat Accessories", "Travel Strollers"],
        "Nursery Furniture": ["Crib Bedding Sets", "Baby Cribs", "Changing Tables", "Crib Mattresses", "Gliders & Rockers", "Nursery Dressers", "Bassinets", "Cradles", "Nursery Storage", "Crib Mobiles"],
        "Bathing & Skin Care": ["Baby Bathtubs", "Baby Shampoo", "Baby Body Wash", "Baby Lotion", "Baby Oil", "Baby Powder", "Baby Towels", "Baby Washcloths", "Baby Hair Brushes", "Diaper Creams"],
        "Baby Toys": ["Baby Rattles", "Teething Toys", "Baby Playmats", "Soft Toys", "Baby Mirrors", "Activity Centers", "Crib Toys", "Baby Mobiles", "Baby Gyms", "Sensory Toys"],
        "Maternity Care": ["Maternity Dresses", "Maternity Jeans", "Maternity Tops", "Maternity Leggings", "Maternity Underwear", "Maternity Support Belts", "Maternity Pillow", "Maternity Swimwear", "Breastfeeding Pillows", "Nursing Bras"],
        "Baby Safety": ["Baby Monitors", "Baby Gates", "Outlet Covers", "Cabinet Locks", "Edge Guards", "Safety Corner Protectors", "Door Locks", "Window Guards", "Baby Proofing Kits", "Baby Proofing Accessories"],
        "Baby Health": ["Baby Thermometers", "Baby Nasal Aspirators", "Baby Nail Clippers", "Baby Grooming Kits", "Baby First Aid Kits", "Baby Humidifiers", "Baby Oral Care", "Baby Medicine Dispensers", "Baby Skin Care", "Baby Sunscreen"]
    },
    "Art & Collectibles": {
        "Paintings": ["Oil Paintings", "Watercolor Paintings", "Acrylic Paintings", "Abstract Paintings", "Landscape Paintings", "Portrait Paintings", "Modern Art Paintings", "Canvas Paintings", "Framed Paintings", "Fine Art Paintings"],
        "Sculptures": ["Bronze Sculptures", "Wooden Sculptures", "Stone Sculptures", "Abstract Sculptures", "Figurative Sculptures", "Contemporary Sculptures", "Sculpture Statues", "Outdoor Sculptures", "Metal Sculptures", "Glass Sculptures"],
        "Prints & Posters": ["Art Prints", "Vintage Posters", "Fine Art Prints", "Canvas Prints", "Photography Prints", "Movie Posters", "Music Posters", "Framed Prints", "Poster Art", "Limited Edition Prints"],
        "Antiques": ["Antique Furniture", "Antique Jewelry", "Antique Coins", "Antique Watches", "Antique Books", "Antique Silverware", "Antique Ceramics", "Antique Artifacts", "Antique Lamps", "Antique Rugs"],
        "Rare Books": ["First Edition Books", "Rare Manuscripts", "Vintage Books", "Rare Fiction Books", "Rare Non-Fiction Books", "Collectible Books", "Signed Books", "Rare Poetry Books", "Rare Children's Books", "Rare Science Fiction Books"],
        "Coins & Stamps": ["Rare Coins", "Ancient Coins", "Collectible Coins", "Rare Stamps", "Vintage Stamps", "World Coins", "Gold Coins", "Silver Coins", "Numismatic Coins", "Philatelic Stamps"],
        "Vintage Collectibles": ["Vintage Toys", "Vintage Cameras", "Vintage Clothing", "Vintage Accessories", "Vintage Jewelry", "Vintage Vinyl Records", "Vintage Board Games", "Vintage Kitchenware", "Vintage Home Decor", "Vintage Postcards"],
        "Handmade Crafts": ["Handmade Jewelry", "Handmade Pottery", "Handmade Candles", "Handmade Soaps", "Handmade Textiles", "Handmade Woodwork", "Handmade Glassware", "Handmade Ceramics", "Handmade Sculptures", "Handmade Paper Crafts"],
        "Photography Art": ["Photography Prints", "Photography Books", "Photography Posters", "Photography Canvas Art", "Photography Framed Art", "Photography Wall Decals", "Photography Calendars", "Photography Greeting Cards", "Photography Coffee Table Books", "Photography Postcards"],
        "Collectible Cards": ["Trading Cards", "Sports Cards", "Magic: The Gathering Cards", "Pokémon Cards", "Yu-Gi-Oh! Cards", "Collectible Card Games", "Non-Sports Cards", "Vintage Trading Cards", "Collectible Card Sleeves", "Collectible Card Albums"]
    }
}