{
   "Electronics": {
       "Smartphones & Accessories",
       "Computers & Laptops",
       "Cameras & Photography",
       "Televisions & Home Theater",
       "Audio & Hi-Fi",
       "Wearable Technology",
       "Video Games & Consoles",
       "Tablets & E-Readers",
       "Networking & Wireless",
       "Home Automation & Security"
   },
   "Fashion": {
       "Casual Wear",
       "Formal Wear",
       "Sportswear",
       "Footwear",
       "Accessories",
       "Lingerie & Sleepwear",
       "Swimwear",
       "Ethnic Wear",
       "Kids' Fashion",
       "Plus Size Clothing"
   },
   "Home & Kitchen": {
       "Cookware & Bakeware",
       "Kitchen Appliances",
       "Dining & Tableware",
       "Bedding & Linens",
       "Home Décor",
       "Storage & Organization",
       "Cleaning Supplies",
       "Home Improvement Tools",
       "Furniture",
       "Smart Home Devices"
   },
   "Beauty & Personal Care": {
       "Skincare",
       "Haircare",
       "Makeup",
       "Fragrances",
       "Bath & Body",
       "Men's Grooming",
       "Oral Care",
       "Nail Care",
       "Tools & Accessories",
       "Natural & Organic"
   },
   "Sports & Outdoors": {
       "Fitness & Exercise Equipment",
       "Outdoor Recreation",
       "Team Sports",
       "Water Sports",
       "Camping & Hiking",
       "Cycling",
       "Golf",
       "Winter Sports",
       "Sports Apparel",
       "Sports Nutrition"
   },
   "Automotive": {
       "Car Accessories",
       "Motorbike Accessories",
       "Car Parts",
       "Tires & Wheels",
       "Oils & Fluids",
       "Car Electronics",
       "Tools & Equipment",
       "Car Care",
       "Motorcycle Parts",
       "GPS & Navigation"
   },
   "Books & Stationery": {
       "Fiction",
       "Non-Fiction",
       "Children's Books",
       "Academic & Textbooks",
       "Journals & Diaries",
       "Art Supplies",
       "Office Supplies",
       "Calendars & Planners",
       "Greeting Cards",
       "Writing Instruments"
   },
   "Toys & Games": {
       "Educational Toys",
       "Board Games & Puzzles",
       "Action Figures & Collectibles",
       "Dolls & Plush Toys",
       "Outdoor Play",
       "Electronic Toys",
       "Building & Construction Toys",
       "Arts & Crafts",
       "Pretend Play",
       "Remote Control Toys"
   },
   "Grocery & Gourmet Food": {
       "Fresh Produce",
       "Bakery & Bread",
       "Dairy & Eggs",
       "Meat & Seafood",
       "Pantry Staples",
       "Snacks & Sweets",
       "Beverages",
       "Organic Foods",
       "International Foods",
       "Special Diet Foods"
   },
   "Health & Wellness": {
       "Supplements & Vitamins",
       "Personal Care",
       "Fitness & Yoga Equipment",
       "Health Monitors & Devices",
       "Weight Management",
       "Herbal & Alternative Remedies",
       "Sexual Wellness",
       "First Aid & Medical Supplies",
       "Mental Wellness",
       "Sleep Aids"
   },
   "Pet Supplies": {
       "Dog Supplies",
       "Cat Supplies",
       "Fish & Aquarium",
       "Small Animal Supplies",
       "Bird Supplies",
       "Reptile & Amphibian Supplies",
       "Horse Supplies",
       "Pet Food & Treats",
       "Pet Grooming",
       "Pet Health & Wellness"
   },
   "Gardening & Outdoor Living": {
       "Plants & Seeds",
       "Garden Tools",
       "Outdoor Furniture",
       "Grills & Outdoor Cooking",
       "Pools & Water Fun",
       "Landscaping & Décor",
       "Pest Control",
       "Outdoor Lighting",
       "Garden Structures",
       "Hydroponics & Greenhouses"
   },
   "Music & Entertainment": {
       "Musical Instruments",
       "Recording & Studio Equipment",
       "Streaming Services",
       "Concert & Event Tickets",
       "Movies & TV Shows",
       "Books & Magazines",
       "Board Games & Puzzles",
       "Collectibles & Memorabilia",
       "Vinyl Records & CDs",
       "Electronic Entertainment"
   },
   "Furniture & Home Decor": {
       "Sofas & Couches",
       "Beds & Bedroom Furniture",
       "Tables & Chairs",
       "Storage & Organization",
       "Lighting & Lamps",
       "Wall Art & Decor",
       "Rugs & Carpets",
       "Home Textiles",
       "Outdoor Furniture",
       "Office Furniture"
   },
   "Jewelry & Accessories": {
       "Necklaces & Pendants",
       "Rings",
       "Earrings",
       "Bracelets & Bangles",
       "Watches",
       "Fine Jewelry",
       "Fashion Jewelry",
       "Handbags & Wallets",
       "Sunglasses",
       "Scarves & Wraps"
   },
   "Office Supplies": {
       "Writing Instruments",
       "Paper Products",
       "Desk Accessories",
       "Organizers & Planners",
       "Printers & Scanners",
       "Office Furniture",
       "Office Electronics",
       "Binders & Folders",
       "Mailing & Shipping Supplies",
       "Educational Supplies"
   },
   "Travel & Luggage": {
       "Suitcases & Travel Bags",
       "Backpacks",
       "Travel Accessories",
       "Travel Electronics",
       "Camping & Hiking Gear",
       "Travel Clothing",
       "Travel Books & Guides",
       "Maps & Navigation",
       "Travel Security",
       "Specialty Luggage"
   },
   "Crafts & Hobbies": {
       "Painting & Drawing Supplies",
       "Sewing & Fabric",
       "Knitting & Crochet",
       "Scrapbooking & Paper Crafts",
       "Jewelry Making",
       "Woodworking",
       "Model Building",
       "Collectibles",
       "Photography",
       "Candle & Soap Making"
   },
   "Baby Products": {
       "Baby Clothing & Accessories",
       "Diapers & Wipes",
       "Feeding & Nursing",
       "Strollers & Car Seats",
       "Nursery Furniture",
       "Bathing & Skin Care",
       "Baby Toys",
       "Maternity Care",
       "Baby Safety",
       "Baby Health"
   },
   "Art & Collectibles": {
       "Paintings",
       "Sculptures",
       "Prints & Posters",
       "Antiques",
       "Rare Books",
       "Coins & Stamps",
       "Vintage Collectibles",
       "Handmade Crafts",
       "Photography Art",
       "Collectible",
       "Cards"
   }
}